import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "pokeapi-ui/dist/pokeapi-ui.css";
import { css } from "@/styled-system/css";
import HeaderContainer from "./components/header/headerContainer";
import QueryProvider from "./providers/queryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryProvider>
          {/* <Header /> */}
          <HeaderContainer />
          <main
            className={css({
              pt: 16,
            })}
          >
            {children}
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
